<?php

namespace App\Console\Commands;

use App\Models\CatalogEntry;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ImportFiveToolsCommand extends Command
{
    protected $signature = 'compendium:import
        {file : NDJSON generated by scripts/build-compendium.py}
        {--dry-run : Calcula o diff sem gravar alterações}
        {--deactivate-missing : Marca como inativas entradas 5etools que não aparecem nesta carga}';

    protected $description = 'Importa o catálogo normalizado 5etools sem alterar o acervo Open5e.';

    public function handle(): int
    {
        $path = $this->argument('file');
        if (! is_file($path) || ! is_readable($path)) {
            $this->error('Arquivo não encontrado.');

            return self::FAILURE;
        }
        $fileHash = hash_file('sha256', $path);
        $batchId = substr($fileHash, 0, 32).'-'.Str::lower(Str::random(16));
        $rows = [];
        $file = new \SplFileObject($path);
        foreach ($file as $lineNumber => $line) {
            if (! trim($line)) {
                continue;
            }
            try {
                $row = json_decode($line, true, flags: JSON_THROW_ON_ERROR);
            } catch (\JsonException $e) {
                $this->error('JSON inválido na linha '.($lineNumber + 1).': '.$e->getMessage());

                return self::FAILURE;
            }
            if (! is_array($row) || ! is_string($row['slug'] ?? null) || ! preg_match('/^[a-f0-9]{64}$/', $row['slug'])
                || ! is_string($row['kind'] ?? null) || ! is_string($row['name'] ?? null) || trim($row['name']) === ''
                || ! is_string($row['source'] ?? null) || ! in_array($row['edition'] ?? null, ['5e-2014', '5e-2024'], true)
                || ! is_array($row['data'] ?? null) || ($row['data']['format'] ?? null) !== '5etools') {
                $this->error('Entrada inválida na linha '.($lineNumber + 1).'.');

                return self::FAILURE;
            }
            if (isset($rows[$row['slug']])) {
                $this->error('Slug duplicado na linha '.($lineNumber + 1).': '.$row['slug']);

                return self::FAILURE;
            }
            $encoded = json_encode($row['data'], JSON_THROW_ON_ERROR | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
            $row['data'] = $encoded;
            $row['content_hash'] = hash('sha256', implode('|', [
                $row['kind'], $row['name'], $row['source'], $row['edition'], (string) ($row['level'] ?? ''), $encoded,
            ]));
            $row['active'] = true;
            $row['import_batch'] = $batchId;
            $rows[$row['slug']] = $row;
        }
        $existing = CatalogEntry::whereIn('slug', array_keys($rows))->get(['slug', 'content_hash', 'kind', 'name', 'source', 'edition', 'level', 'data'])->keyBy('slug');
        $created = 0;
        $updated = 0;
        $unchanged = 0;
        foreach ($rows as $slug => $row) {
            $current = $existing->get($slug);
            if (! $current) {
                $created++;

                continue;
            }
            $currentHash = $current->content_hash ?: hash('sha256', implode('|', [
                $current->kind, $current->name, $current->source, $current->edition, (string) ($current->level ?? ''),
                json_encode($current->data, JSON_THROW_ON_ERROR | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
            ]));
            if (hash_equals($currentHash, $row['content_hash'])) {
                $unchanged++;
            } else {
                $updated++;
            }
        }
        $deactivated = 0;
        if ($this->option('deactivate-missing')) {
            $deactivated = CatalogEntry::where('active', true)
                ->where('data->format', '5etools')
                ->whereNotIn('slug', array_keys($rows))->count();
        }
        $this->table(['Novas', 'Alteradas', 'Iguais', 'Ausentes'], [[$created, $updated, $unchanged, $deactivated]]);
        if ($this->option('dry-run')) {
            $this->info('Dry-run concluído; nenhuma alteração gravada.');

            return self::SUCCESS;
        }

        DB::transaction(function () use ($rows, $batchId, $fileHash, $created, $updated, $unchanged, &$deactivated) {
            if ($this->option('deactivate-missing')) {
                CatalogEntry::where('active', true)->where('data->format', '5etools')->update(['active' => false]);
            }
            foreach (array_chunk(array_values($rows), 100) as $chunk) {
                CatalogEntry::upsert($chunk, ['slug'], ['kind', 'name', 'source', 'edition', 'level', 'data', 'active', 'import_batch', 'content_hash']);
            }
            DB::table('catalog_imports')->insert([
                'batch_id' => $batchId,
                'file_hash' => $fileHash,
                'entry_count' => count($rows),
                'created_count' => $created,
                'updated_count' => $updated,
                'unchanged_count' => $unchanged,
                'deactivated_count' => $deactivated,
                'imported_at' => now(),
            ]);
        });
        $this->info(count($rows)." entradas processadas no lote {$batchId}.");

        return self::SUCCESS;
    }
}
